import type { Metadata } from "next";
import { Geist, Geist_Mono, DM_Sans, Noto_Serif } from "next/font/google";
import "@fortawesome/fontawesome-free/css/all.min.css"
// Import Swiper styles
import 'swiper/css';
import "./globals.css";
import Navbar from "./_components/navbar/navbar";
import { cn } from "@/lib/utils";
import { Toaster } from "@/components/ui/toast";
import Providers from "@/Providers";


const notoSerifHeading = Noto_Serif({subsets:['latin'],variable:'--font-heading'});

const dmSans = DM_Sans({subsets:['latin'],variable:'--font-sans'});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Frash Cart",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={cn("h-full", "antialiased", geistSans.variable, geistMono.variable, "font-sans", dmSans.variable, notoSerifHeading.variable)}
    >
      <body className="min-h-full flex flex-col">
        <Providers>

            <Navbar />
            {children}
            <Toaster />
        </Providers>
        </body>
    </html>
  );
}
